### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Tangolin** [jayleicn/ClipBERT#40]
I followed the set up instructions pretty much step by step and bumped into this error:
```
12/30/2021 06:50:47 - INFO - __main__ -     Total #steps = 175250
12/30/2021 06:50:47 - INFO - __main__ -     Validate every 1800 steps, in total 98 times
Traceback (most recent call last):
  File "src/tasks/run_video_retrieval.py", line 833, in <module>
    start_training(input_cfg)
  File "src/tasks/run_video_retrieval.py", line 385, in start_training
    optimizer.step()
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 359, in new_step
    self._master_params_to_model_params()
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 22, in _master_params_to_model_params
    1.0)
  File "/opt/conda/lib/python3.6/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
Might you have any experience with this error? If not I will redirect it to the APEX repo instead. Thanks in advance!

**Comment by jayleicn** [comment]
Hi @Tangolin, I did not see this before, please redirect to apex repo.

**Comment by Tangolin** [comment]
Hi @jayleicn, is it possible then to run the program without the apex library? Or is the apex library essential in the code?

**Comment by jayleicn** [comment]
No, it is not. You can probably use the newer PyTorch version with built-in fp16 support. Though we did not try this, I assume there is nothing in this codebase that would prevent this change.
