### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'

### ISSUE THREAD

**Issue by RishiHazra** [jayleicn/ClipBERT#48]
While running run_video_qa.py with tgif_qa_action. I'm unable to figure out if there is something wrong with the dataset or Detectron2. I've installed the latest version.

```
08/18/2022 22:46:34 - INFO - __main__ -   device: cuda:0 n_gpu: 1, rank: 0, 16-bits training: True
08/18/2022 22:46:34 - INFO - __main__ -   Setup model...
08/18/2022 22:46:34 - INFO - __main__ -   setup e2e model
Traceback (most recent call last):
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/tasks/run_video_qa.py", line 722, in <module>
    start_training(input_cfg)
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/tasks/run_video_qa.py", line 385, in start_training
    model = setup_model(cfg, device=device)
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/tasks/run_video_qa.py", line 193, in setup_model
    transformer_cls=transformer_model_cls)
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/modeling/e2e_model.py", line 25, in __init__
    config=config, input_format=input_format)
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/modeling/grid_feat.py", line 42, in __init__
    self.feature = build_model(self.detectron2_cfg)
  File "/home/rishihazra/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/rishihazra/detectron2/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/rishihazra/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/rishihazra/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 77, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
  File "/home/rishihazra/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/home/rishihazra/PycharmProjects/VisionLangaugeGrounding/baselines/ClipBERT/src/modeling/grid_feats/roi_heads.py", line 175, in __init__
    super(StandardROIHeads, self).__init__(cfg, input_shape)
  File "/home/rishihazra/detectron2/detectron2/config/config.py", line 190, in wrapped
    init_func(self, **explicit_args)
TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'

Process finished with exit code 1

```

**Comment by wonjiny** [comment]
I have the exactly same issue. Did you solve it?

**Comment by sushilkhadkaanon** [comment]
Yeah same issue @RishiHazra @wonjiny  Did you guys solve this?

**Comment by shaswati1** [comment]
Is there any solution for this issue?
