### ISSUE TITLE
lmdb.Error: /img/msrvtt: No such file or directory

### ISSUE THREAD

**Issue by giraffeooo** [jayleicn/ClipBERT#54]
Hello, the following problems occurred while the code was running, but I am not sure where this/img/msrvtt is or where the address was passed. In the initial get_ video_ retrieval_ args() function also failed to find the relevant parameter settings. I look forward to your reply!

03/27/2023 07:05:02 - INFO - __main__ -   group_datalist 140200
Traceback (most recent call last):
  File "src/tasks/run_video_retrieval.py", line 823, in <module>
    start_training(input_cfg)
  File "src/tasks/run_video_retrieval.py", line 313, in start_training
    train_loader, val_loader = setup_dataloaders(cfg, tokenizer)
  File "src/tasks/run_video_retrieval.py", line 168, in setup_dataloaders
    cfg=cfg, tokenizer=tokenizer, is_train=True
  File "src/tasks/run_video_retrieval.py", line 101, in mk_video_ret_dataloader
    random_sample_clips=cfg.random_sample_clips
  File "/clipbert/src/datasets/dataset_video_retrieval.py", line 29, in __init__
    max_img_size=max_img_size, max_txt_len=max_txt_len)
  File "/clipbert/src/datasets/dataset_base.py", line 198, in __init__
    create=False)  # readahead=not _check_distributed()
lmdb.Error: /img/msrvtt: No such file or directory

**Comment by JisenRen** [comment]
I guess you should download the MSR-VTT dataset and run the preprocessing script inside the repo to generate the LMDB dataset.

**Comment by saimaafrin** [comment]
Im also having this issue. Did you solve it?
